version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: orb-slam3-python:dev
    container_name: orb-slam3-python-dev
    volumes:
      - .:/opt/ORB_SLAM3-PythonBinding
    tty: true